
#include "phy_drv.h"

#define VERIPHY_ABS(x) (((x) < 0) ? -(x) : (x))
#define VERIPHY_MAX_ABS_COEFF_ANOM_INVALID_NOISE  70
#define VERIPHY_MAX_ABS_COEFF_LEN_INVALID_NOISE  180


#define VTSS8XX8_VERIPHY_STATE_DONEBIT 0x80
#define VERIPHY_DISCARD 0x80
#define VTSS8XX8_VERIPHY_STATE_IDLE 0x00
#define VERIPHY_FFEinit4_7anomSearch   0
#define VERIPHY_FFEinit4_7lengthSearch 1


typedef enum
{
    VTSS8XX8_VERIPHY_STATE_IDLE_0            = VTSS8XX8_VERIPHY_STATE_IDLE,
    VTSS8XX8_VERIPHY_STATE_INIT_0            = VTSS8XX8_VERIPHY_STATE_IDLE + 0x01,
    VTSS8XX8_VERIPHY_STATE_INIT_1            = VTSS8XX8_VERIPHY_STATE_IDLE + 0x02,
    VTSS8XX8_VERIPHY_STATE_INIT_LINKDOWN     = VTSS8XX8_VERIPHY_STATE_IDLE + 0x03,
    VTSS8XX8_VERIPHY_STATE_INIT_ANOMSEARCH_0 = VTSS8XX8_VERIPHY_STATE_IDLE + 0x04,
    VTSS8XX8_VERIPHY_STATE_INIT_ANOMSEARCH_1 = VTSS8XX8_VERIPHY_STATE_IDLE + 0x05,
    VTSS8XX8_VERIPHY_STATE_ANOMSEARCH_0      = VTSS8XX8_VERIPHY_STATE_IDLE + 0x06,
    VTSS8XX8_VERIPHY_STATE_ANOMSEARCH_1      = VTSS8XX8_VERIPHY_STATE_IDLE + 0x07,
    VTSS8XX8_VERIPHY_STATE_ANOMSEARCH_2      = VTSS8XX8_VERIPHY_STATE_IDLE + 0x08,
    VTSS8XX8_VERIPHY_STATE_ANOMSEARCH_3      = VTSS8XX8_VERIPHY_STATE_IDLE + 0x09,
    VTSS8XX8_VERIPHY_STATE_INIT_CABLELEN     = VTSS8XX8_VERIPHY_STATE_IDLE + 0x0a,
    VTSS8XX8_VERIPHY_STATE_GETCABLELEN_0     = VTSS8XX8_VERIPHY_STATE_IDLE + 0x0b,
    VTSS8XX8_VERIPHY_STATE_GETCABLELEN_1     = VTSS8XX8_VERIPHY_STATE_IDLE + 0x0c,
    VTSS8XX8_VERIPHY_STATE_PAIRSWAP          = VTSS8XX8_VERIPHY_STATE_IDLE + 0x0d,
    VTSS8XX8_VERIPHY_STATE_ABORT             = (VTSS8XX8_VERIPHY_STATE_DONEBIT | 0),
    VTSS8XX8_VERIPHY_STATE_FINISH            = (VTSS8XX8_VERIPHY_STATE_DONEBIT | 0x0e)
} vtss8xx8_veriphy_task_state_t;

/* PHY register pages */
#define VTSS8XX8_PHY_PAGE_STANDARD 0x0000 /* Standard registers */
#define VTSS8XX8_PHY_PAGE_EXTENDED 0x0001 /* Extended registers */
#define VTSS8XX8_PHY_PAGE_TEST     0x2A30 /* Test registers */
#define VTSS8XX8_PHY_PAGE_TR       0x52B5 /* Token ring registers */

#define VTSS_8xx8_VERIPHY_CTRL_REG1 24
#define VTSS_8xx8_VERIPHY_CTRL_REG2 25
#define VTSS_8xx8_VERIPHY_CTRL_REG3 26

#define VERIPHY_RC(expr) { int32 rc = (expr); if (rc != RESULT_OK) return rc; }

int32 vtss8xx8_veriphy_task_start(phy_handle_t* phy_handle, uint8 mode);
int32 vtss8xx8_veriphy_get_result(phy_handle_t* phy_handle);

