
#ifndef __HSRV_ERROR_H__
#define __HSRV_ERROR_H__

#include "glb_const.h"

typedef enum
{
    HSRV_E_NONE = 0,
    HSRV_E_NO_MEMORY = GLB_HSRV_ERROR_BASE,/*-3000*/
    HSRV_E_INVALID_PARAM,
    HSRV_E_INVALID_PTR,
    HSRV_E_SOCK_CREATE_ERR,
    HSRV_E_SOCK_BIND_ERR,
    
    HSRV_E_SOCK_ACCEPT_ERR,  /*-2995*/
    HSRV_E_SOCK_READ_ERR,
    HSRV_E_NOT_INIT,
    HSRV_E_SOCK_WRITE_ERR,   
    HSRV_E_ENTRY_NOT_EXIST,
    
    HSRV_E_ENTRY_EXIST,             /*-2990*/
    HSRV_E_ENTRY_DIFFERENT,    
    HSRV_E_PORT_NOT_EXIST, 
    HSRV_E_RESOURCE_FULL,
    HSRV_E_CREATE_INTF_FAILED,
    
    HSRV_E_ADD_INTF_FAILED,
    HSRV_E_FDB_ENTRY_NOT_EXIT,
    HSRV_E_EXCEED_MAX_SIZE,
    HSRV_E_INTF_ISNT_L2,
    HSRV_E_NO_LABEL,
    
    HSRV_E_NO_ACL, /*-2980*/
    HSRV_E_NO_ACE,
    HSRV_E_ACL_CONFLICT,
    HSRV_E_QOS_NO_LABEL,
    HSRV_E_FDB_CANT_OW_SECURITY_ENTRY,
    
    HSRV_E_HAVE_INIT,
    HSRV_E_MSG_ENCODE_ERR,
    HSRV_E_RMT_WRITE_ERR,
    HSRV_E_MSG_SESSION_NOT_EXIST,
    HSRV_E_SOCK_IOCTL_ERR,

    HSRV_E_INTERNAL_PORT_CREATED, /*-2970*/
    HSRV_E_CB_ERROR,
    HSRV_E_OPENFLOW_INVALID_ACTION,
    HSRV_E_OPENFLOW_RESOURCE_FULL,
    HSRV_E_OPENFLOW_MPLS_PARSE_ACTIONLIST_SEQ_FAILED,
    HSRV_E_OPENFLOW_MPLS_ALLOC_RESOURCE_FAILED,
    HSRV_E_OPENFLOW_MPLS_TUNNELID_RESOURCE_FULL,
    HSRV_E_INTERFACE_NOT_EXIT,
    HSRV_E_DATA_IS_TOO_LONG,   /* Modified by shengx for to cpu mirror data 2018-09-10 */
    HSRV_E_DATA_IS_NULL,       

    HSRV_E_FAIL, /*-2960*/
    HSRV_E_MAX
} hsrv_error_t;

#endif /*__HSRV_ERROR_H__*/


