#! /bin/sh


/bin/busybox --install -s /bin

mount -t proc none /proc
mount -t sysfs sysfs /sys
mkdir /dev/pts
mount -t devpts none /dev/pts

mknod /dev/ttyAMA0 c 204 64
mknod /dev/ttyAMA1 c 204 65
mknod /dev/ttyS000 c 204 64
mknod /dev/null    c 1 3

/usr/sbin/udevd --daemon 
/usr/sbin/udevstart 

ipaddr=`printenv selfip 2>/dev/null`

if [ "$ipaddr" = "" ]; then
    # No ipaddr in U-Boot, set to default address.
    ifconfig eth0 192.168.0.103 netmask 255.255.255.0 up
else
    ifconfig eth0 $ipaddr netmask 255.255.254.0 up
fi

telnetd &

while true; do          
    if [ -f /tmp/.fs_mount_done ] ; then
        break;           
    fi
    sleep 1;
    let wait_count=wait_count+1
    
    if [ $wait_count -ge 50 ] ; then
        break;
    fi
done

if [ -f /mnt/flash/boot/.enter_minios ];then
	exit
fi

cmdline=`cat /proc/cmdline | grep "TftpFile"`
if [ ! -z "$cmdline" ]; then
	#imageandright=`echo ${cmdline:34}`
	#imagename=`echo ${imageandright%% *}`
	#serveripandleft=`echo ${cmdline:21}`
	#serverip=`echo ${serveripandleft%%:*}`
	
	imageandright=$(echo $cmdline | cut -d : -f 3)
	imagename=$(echo $imageandright | cut -d ' ' -f 1)
	serveripandleft=$(echo $cmdline | cut -d : -f 2)
	serverip=$(echo $serveripandleft | cut -c 3-)
	
	tftp $serverip -g -r $imagename -l /$imagename
	cd /
	dd if=$imagename of=mainramfs.lzma ibs=1024 obs=1024 skip=8192
	if [ -f mainramfs ];then
        rm -rf mainramfs        
	fi
	unlzma mainramfs.lzma
	cpio -i -d -H newc -u -F mainramfs 
	rm -rf mainramfs 
	/etc/rc.sysinit
	exit
fi

if [ ! -f /mnt/flash/boot/mainramfs ]; then
	exit
fi
cp /mnt/flash/boot/mainramfs /mainramfs
cd /
cpio -i -d -H newc -u -F mainramfs  
rm -rf mainramfs 
/etc/rc.sysinit
