/* This file is automatically generated by configure.  Do not modify by hand. */
  if (should_init("snmpNotifyTable")) shutdown_snmpNotifyTable();
  if (should_init("snmpTargetAddrEntry")) shutdown_snmpTargetAddrEntry();
  if (should_init("snmpTargetParamsEntry")) shutdown_snmpTargetParamsEntry();
  if (should_init("snmpMPDStats_5_5")) shutdown_snmpMPDStats_5_5();
  if (should_init("usmStats_5_5")) shutdown_usmStats_5_5();
  if (should_init("snmpNotifyFilterTable")) shutdown_snmpNotifyFilterTable();
  if (should_init("cpu")) shutdown_cpu();
  if (should_init("notification_log")) shutdown_notification_log();
  if (should_init("ifTable")) shutdown_ifTable();
