#! /bin/sh

set -e

CONFFILE="/etc/redis/sentinel.conf"

if [ "$1" = "purge" ]
then
	dpkg-statoverride --remove ${CONFFILE} || test $? -eq 2
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d redis-sentinel remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask redis-sentinel.service >/dev/null
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge redis-sentinel.service >/dev/null
		deb-systemd-helper unmask redis-sentinel.service >/dev/null
	fi
fi
# End automatically added section

