SRCS += $(wildcard device/sysenv/*.c)

include $(MK_DIR)/sys.mk
LIB = sysenv
SRCS += $(wildcard *.c)

include $(DRV_TOP_DIR)/Makefile.include
CPPFLAGS += -I$(DRV_TOP_DIR)/device/sysenv
CPPFLAGS += -I$(DRV_TOP_DIR)/device/eeprom
CPPFLAGS += -I$(DRV_TOP_DIR)/bus/cpu/i2c/include

include $(MK_DIR)/lib.mk
