all_targets = libdal

all_targets += lkm_linux_dal_io

all: $(all_targets) FORCE
clean: $(addprefix clean_,$(all_targets)) FORCE

libdal: FORCE
	make -f Makefile_libdal.ctc

clean_libdal: FORCE
	make -f Makefile_libdal.ctc clean

lkm_linux_dal_io: FORCE
	make -C $(SDK_DIR)/dal/src/linux/kernel -f Makefile.ctc


clean_lkm_linux_dal_io: FORCE
	make -C $(SDK_DIR)/dal/src/linux/kernel -f Makefile.ctc clean

.PHONY: FORCE
FORCE:

