dtb-$(CONFIG_ARCH_CTC5236) += ctc5236-emu.dtb
dtb-$(CONFIG_ARCH_CTC5236) += ctc5236-vel.dtb
dtb-$(CONFIG_ARCH_CTC5236) += ctc5236-vel-qspi.dtb
dtb-$(CONFIG_ARCH_CTC5236) += e530-ctc5236.dtb
always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
