
include ../../Makefile.env.inc

include $(MK_DIR)/sys.mk

LIB = afx
SRCS = $(shell find -name "*.c")

#CPPFLAGS += -I$(ROOT_DIR)/lib/sal/include
#CPPFLAGS += -D_GNU_SOURCE
#CFLAGS += -Werror -Wall

include $(MK_DIR)/lib.mk
