#ifndef __CTCLIB_ERROR_H__
#define __CTCLIB_ERROR_H__
#include "glb_const.h"
enum ctclib_err
{
    CTCLIB_E_NONE = 0,
    CTCLIB_E_NO_MEMORY = GLB_CTCLIB_ERROR_BASE,
    CTCLIB_E_INVALID_PARAM,
    CTCLIB_E_INVALID_PTR,
    CTCLIB_E_CREATE_MEM_CACHE_FAIL,
    CTCLIB_E_FAIL_CREATE_MUTEX,
    
    CTCLIB_E_MAX
};

#endif /*__CTCLIB_ERROR_H__*/
