# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Use docker for quicker builds, it now allows https://docs.travis-ci.com/user/apt/
sudo: false

# Test build with both GCC and Clang (LLVM)
compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "OAx9MdLgm+ZpCo/h65praDhKl35RgHEQRFR1qa5fLFrVxqFIusXFl4/A+xSpY+EYcmN0Vcsn5Z79dy3DqK6Njbt14s56NH1mvuDw7SxkFDijwZkJTmgjgCiDM+Hn3Vwjk9WYX0PNifX8Mcm0Zp9sci/koW523ltJdWC7ULvFzK8="

addons:
  apt:
    packages:
      - tree
  coverity_scan:
    project:
      name: "troglobit/pimd"
      description: "pimd | The Original PIM-SM Daemon"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && ./configure --enable-rsrr"
    build_command:   "make clean all"
    branch_pattern: dev

script:
  - ./autogen.sh
  - ./configure --enable-rsrr --prefix=
  - make clean
  - make V=1 -j5
  - DESTDIR=~/tmp make install-strip
  - tree ~/tmp
  - ldd ~/tmp/sbin/pimd
  - size ~/tmp/sbin/pimd
  - ~/tmp/sbin/pimd -h
