
#ifndef __GENLOG_ID_PRIV_H__
#define __GENLOG_ID_PRIV_H__

const static osp_log_info_t gLogInfoArr[LOG_ID_MAX] =
{
    {
        LOG_FAN_3_FAIL,
        E_ERROR,
        "FAN-FAIL",
        "Fan %s in slot %d is fail",
    },
    {
        LOG_FAN_4_OK,
        E_WARNING,
        "FAN-OK",
        "Fan %s in slot %d is ok",
    },
    {
        LOG_INTERFACE_4_CREATE,
        E_WARNING,
        "INTERFACE-CREATE",
        "Create physical interface %s, MAC address is %s, gport is %u",
    },
    {
        LOG_INTERFACE_4_UPDOWN,
        E_WARNING,
        "INTERFACE-UPDOWN",
        "Interface %s state change to %s",
    },
    {
        LOG_INTERFACE_4_ERRDISABLE_ENTER,
        E_WARNING,
        "INTERFACE-ERRDISABLE_ENTER",
        "Interface %s enter %s errdisable state",
    },
    {
        LOG_INTERFACE_4_BANDWIDTH_OVERFLOW,
        E_WARNING,
        "INTERFACE-BANDWIDTH_OVERFLOW",
        "Interface %s %s bandwidth utilization rate over %d percent",
    },
    {
        LOG_INTERFACE_4_BANDWIDTH_RESUME,
        E_WARNING,
        "INTERFACE-BANDWIDTH_RESUME",
        "Interface %s %s bandwidth utilization rate resume under %d percent",
    },
    {
        LOG_INTERFACE_4_DROP_OVERFLOW,
        E_WARNING,
        "INTERFACE-DROP_OVERFLOW",
        "Interface %s %s drop %llu packets in %d minutes",
    },
    {
        LOG_INTERFACE_4_DROP_RESUME,
        E_WARNING,
        "INTERFACE-DROP_RESUME",
        "Interface %s %s drop resume under %llu packets in %d minutes",
    },
    {
        LOG_INTERFACE_4_ERRDISABLE_EXIT,
        E_WARNING,
        "INTERFACE-ERRDISABLE_EXIT",
        "Interface %s exit errdisable state for %s",
    },
    {
        LOG_INTERFACE_4_CRCPKT,
        E_WARNING,
        "INTERFACE-CRCPKT",
        "Interface %s newly receives %llu (total %llu) CRC error packets",
    },
    {
        LOG_LAG_4_ADD,
        E_WARNING,
        "LAG-ADD",
        "LAG interface %s is created",
    },
    {
        LOG_LAG_4_DEL,
        E_WARNING,
        "LAG-DEL",
        "LAG interface %s is deleted",
    },
    {
        LOG_LAG_4_ATTACH_MEMBER,
        E_WARNING,
        "LAG-ATTACH_MEMBER",
        "LAG interface %s attach member %s",
    },
    {
        LOG_LAG_4_DETACH_MEMBER,
        E_WARNING,
        "LAG-DETACH_MEMBER",
        "LAG interface %s detach member %s",
    },
    {
        LOG_LAG_4_CHANGE_ACTIVE,
        E_WARNING,
        "LAG-CHANGE_ACTIVE",
        "LAG interface %s active member %s",
    },
    {
        LOG_LAG_4_CHANGE_INACTIVE,
        E_WARNING,
        "LAG-CHANGE_INACTIVE",
        "LAG interface %s inactive member %s",
    },
    {
        LOG_LLDP_4_ADD_NEIGH,
        E_WARNING,
        "LLDP-ADD_NEIGH",
        "Add LLDP neighbor %s %s on local interface %s",
    },
    {
        LOG_LLDP_4_DEL_NEIGH,
        E_WARNING,
        "LLDP-DEL_NEIGH",
        "Delete LLDP neighbor %s %s on local interface %s for %s",
    },
    {
        LOG_MLAG_4_ESTABLISH,
        E_WARNING,
        "MLAG-ESTABLISH",
        "MLAG session establish with peer %s",
    },
    {
        LOG_MLAG_3_BREAKOFF,
        E_ERROR,
        "MLAG-BREAKOFF",
        "MLAG session break off",
    },
    {
        LOG_OSPF_4_NEIGHCHG,
        E_WARNING,
        "OSPF-NEIGHCHG",
        "OSPF neighbour %s from interface %s state changes (%s -> %s) for %s",
    },
    {
        LOG_PSU_3_ABSENT,
        E_ERROR,
        "PSU-ABSENT",
        "Psu %s in slot %d index %d is absent",
    },
    {
        LOG_PSU_4_PRESENT,
        E_WARNING,
        "PSU-PRESENT",
        "Psu %s in slot %d index %d is present",
    },
    {
        LOG_PSU_3_ABNORMAL,
        E_ERROR,
        "PSU-ABNORMAL",
        "Psu %s in slot %d index %d work is abnormal",
    },
    {
        LOG_PSU_3_ALERT,
        E_ERROR,
        "PSU-ALERT",
        "Psu %s in slot %d index %d is alert",
    },
    {
        LOG_PSU_4_NORMAL,
        E_WARNING,
        "PSU-NORMAL",
        "Psu %s in slot %d index %d work is normal",
    },
    {
        LOG_PSU_4_NOALERT,
        E_WARNING,
        "PSU-NOALERT",
        "Psu %s in slot %d index %d is no alert",
    },
    {
        LOG_PSU_4_PMBUS,
        E_WARNING,
        "PSU-PMBUS",
        "Psu %s in slot %d index %d pmbus info: status_byte: 0x%02x status_word: 0x%04x status_vout: 0x%02x status_iout: 0x%02x status_input: 0x%02x status_temperature: 0x%02x status_cml: 0x%02x status_other: 0x%02x status_mfr_specific: 0x%02x status_fans_1_2: 0x%02x status_fans_3_4: 0x%02x",
    },
    {
        LOG_ROUTE_4_FIB_OVERFLOW,
        E_WARNING,
        "ROUTE-FIB_OVERFLOW",
        "FIB overflow and can not add new route",
    },
    {
        LOG_ROUTE_4_STATIC_ROUTE_OVERFLOW,
        E_WARNING,
        "ROUTE-STATIC_ROUTE_OVERFLOW",
        "static route overflow and can not add new route",
    },
    {
        LOG_ROUTE_6_FIB_OVERFLOW,
        E_INFORMATIONAL,
        "ROUTE-FIB_OVERFLOW",
        "FIB overflow and can not add new route v6",
    },
    {
        LOG_ROUTE_6_STATIC_ROUTE_OVERFLOW,
        E_INFORMATIONAL,
        "ROUTE-STATIC_ROUTE_OVERFLOW",
        "static route overflow and can not add new route v6",
    },
    {
        LOG_ROUTE_4_INDIRECT_ROUTE_OVERFLOW,
        E_WARNING,
        "ROUTE-INDIRECT_ROUTE_OVERFLOW",
        "IPv4 indirect route current %d new add %d max %d, will overflow and can not add new route",
    },
    {
        LOG_ROUTE_6_INDIRECT_ROUTE_OVERFLOW,
        E_INFORMATIONAL,
        "ROUTE-INDIRECT_ROUTE_OVERFLOW",
        "IPv6 indirect route current %d new add %d max %d, will overflow and can not add new route",
    },
    {
        LOG_ROUTE_3_STM_INC_DEC_ERR,
        E_ERROR,
        "ROUTE-STM_INC_DEC_ERR",
        "Stm %s current %d %s %d, max %d, error",
    },
    {
        LOG_ROUTE_4_ECMPGROUP_OVERFLOW,
        E_WARNING,
        "ROUTE-ECMPGROUP_OVERFLOW",
        "ECMP group overflow and can not add new ECMP group to chip",
    },
    {
        LOG_ARP_4_OVERFLOW,
        E_WARNING,
        "ARP-OVERFLOW",
        "ARP table overflow, can not add new ARP entry",
    },
    {
        LOG_SYSTEM_4_REBOOT,
        E_WARNING,
        "SYSTEM-REBOOT",
        "System reboot at %s",
    },
    {
        LOG_SYSTEM_4_STARTUP,
        E_WARNING,
        "SYSTEM-STARTUP",
        "System startup %s",
    },
    {
        LOG_SYSTEM_4_WRITECONFIGURE,
        E_WARNING,
        "SYSTEM-WRITECONFIGURE",
        "Building configuration %s",
    },
    {
        LOG_SYSTEM_4_USERLOGIN,
        E_WARNING,
        "SYSTEM-USERLOGIN",
        "User %s from %s %s system by %s",
    },
    {
        LOG_SYSTEM_4_TIMECHANGE,
        E_WARNING,
        "SYSTEM-TIMECHANGE",
        "System clock has been changed from %s to %s by configuration",
    },
    {
        LOG_SYSTEM_4_TIMEUPDATE,
        E_WARNING,
        "SYSTEM-TIMEUPDATE",
        "System clock has been updated to %s by NTP",
    },
    {
        LOG_SYSTEM_4_TIMEUPDATE_BY_PTP,
        E_WARNING,
        "SYSTEM-TIMEUPDATE_BY_PTP",
        "System clock has been updated to %s by PTP",
    },
    {
        LOG_SYSTEM_4_TIMEZONE_SET,
        E_WARNING,
        "SYSTEM-TIMEZONE_SET",
        "system timezone set to %s (%s %s)",
    },
    {
        LOG_SYSTEM_4_TIMEZONE_CLEAR,
        E_WARNING,
        "SYSTEM-TIMEZONE_CLEAR",
        "system timezone clear from %s (%s %s) to UTC",
    },
    {
        LOG_SYSTEM_4_CPU_THRESHOLD,
        E_WARNING,
        "SYSTEM-CPU_THRESHOLD",
        "CPU usage over %d%% in last %d seconds.",
    },
    {
        LOG_SYSTEM_4_CPU_RESUME,
        E_WARNING,
        "SYSTEM-CPU_RESUME",
        "CPU usage resume under %d%%.",
    },
    {
        LOG_SYSTEM_1_LOAD_CRITICAL,
        E_ALERT,
        "SYSTEM-LOAD_CRITICAL",
        "System load state changes from %s to critical",
    },
    {
        LOG_SYSTEM_2_LOAD_ALERT,
        E_CRITICAL,
        "SYSTEM-LOAD_ALERT",
        "System load state changes from %s to alert",
    },
    {
        LOG_SYSTEM_3_LOAD_WARNING,
        E_ERROR,
        "SYSTEM-LOAD_WARNING",
        "System load state changes from %s to warning",
    },
    {
        LOG_SYSTEM_4_LOAD_NORMAL,
        E_WARNING,
        "SYSTEM-LOAD_NORMAL",
        "System load state changes from %s to normal",
    },
    {
        LOG_SYSTEM_0_MEM_CRITICAL,
        E_EMERGENCY,
        "SYSTEM-MEM_CRITICAL",
        "System memory state changes from %s to critical",
    },
    {
        LOG_SYSTEM_1_MEM_ALERT,
        E_ALERT,
        "SYSTEM-MEM_ALERT",
        "System memory state changes from %s to alert",
    },
    {
        LOG_SYSTEM_3_MEM_WARNING,
        E_ERROR,
        "SYSTEM-MEM_WARNING",
        "System memory state changes from %s to warning",
    },
    {
        LOG_SYSTEM_4_MEM_NORMAL,
        E_WARNING,
        "SYSTEM-MEM_NORMAL",
        "System memory state changes from %s to normal",
    },
    {
        LOG_SYSTEM_3_MEM_PACKETDISCARD,
        E_ERROR,
        "SYSTEM-MEM_PACKETDISCARD",
        "Packet %s will be discarded because the system memory is not enough",
    },
    {
        LOG_TEMPERATURE_3_ALARM,
        E_ERROR,
        "TEMPERATURE-ALARM",
        "%s Temperature %d is out of warn threshold",
    },
    {
        LOG_TEMPERATURE_4_NORMAL,
        E_WARNING,
        "TEMPERATURE-NORMAL",
        "%s Temperature %d has returned to normal",
    },
    {
        LOG_TRANSCEIVER_4_INSERT,
        E_WARNING,
        "TRANSCEIVER-INSERT",
        "Interface %s insert transceiver %s",
    },
    {
        LOG_TRANSCEIVER_4_REMOVE,
        E_WARNING,
        "TRANSCEIVER-REMOVE",
        "Interface %s remove transceiver",
    },
    {
        LOG_TRANSCEIVER_3_ALARM,
        E_ERROR,
        "TRANSCEIVER-ALARM",
        "Interface %s %s enter to %s %s, before is %s",
    },
    {
        LOG_TRANSCEIVER_4_WARN,
        E_WARNING,
        "TRANSCEIVER-WARN",
        "Interface %s %s enter to %s %s, before is %s",
    },
    {
        LOG_TRANSCEIVER_4_NORMAL,
        E_WARNING,
        "TRANSCEIVER-NORMAL",
        "Interface %s %s return to normal, before is %s",
    },
    {
        LOG_FDB_4_OVERFLOW,
        E_WARNING,
        "FDB-OVERFLOW",
        "Add FDB failed for FDB number exceed maximum",
    },
    {
        LOG_FDB_4_FDBLOOP,
        E_WARNING,
        "FDB-FDBLOOP",
        "Interface %s FDB loop for %s VLAN %u, and action is %s",
    },
    {
        LOG_ERPS_4_BLOCK,
        E_WARNING,
        "ERPS-BLOCK",
        "ERPS interface %s instance_id %d state %s",
    },
    {
        LOG_TIMERANGE_4_STATE,
        E_WARNING,
        "TIMERANGE-STATE",
        "TimeRange %s change to %s",
    },
    {
        LOG_BHM_1_REBOOT,
        E_ALERT,
        "BHM-REBOOT",
        "Detect process %s (PID %u) is uncontrolled. System will be reset.",
    },
    {
        LOG_BHM_1_SHUTDOWN,
        E_ALERT,
        "BHM-SHUTDOWN",
        "Detect process %s (PID %u) is uncontrolled. All ports will be shutdown. Please manual reboot system.",
    },
    {
        LOG_BHM_1_WARNING,
        E_ALERT,
        "BHM-WARNING",
        "Detect process %s (PID %u) is uncontrolled. Please manual reboot system.",
    },
    {
        LOG_BHM_1_PROMPT,
        E_ALERT,
        "BHM-PROMPT",
        "Process %s has been uncontrolled. Please manual reboot system.",
    },
    {
        LOG_AAA_4_FAIL,
        E_WARNING,
        "AAA-FAIL",
        "AAA username %s %s %s",
    },
    {
        LOG_DOT1X_4_FAIL,
        E_WARNING,
        "DOT1X-FAIL",
        "DOT1X username %s access %s",
    },
    {
        LOG_ARPINSP_4_RESULT,
        E_WARNING,
        "ARPINSP-RESULT",
        "%s",
    },
    {
        LOG_ARPINSP_3_CHECK,
        E_ERROR,
        "ARPINSP-CHECK",
        "%s",
    },
    {
        LOG_ARPINSP_5_ACL,
        E_NOTICE,
        "ARPINSP-ACL",
        "%s",
    },
    {
        LOG_SFLOW_4_FAIL,
        E_WARNING,
        "SFLOW-FAIL",
        "SFLOW packet fail to %s:%d on socket %d:%s",
    },
    {
        LOG_ARPRATELIMIT_4_EXCEED,
        E_WARNING,
        "ARPRATELIMIT-EXCEED",
        "The port %s receive %d packets on %s, exceed configured value %d,  turn to %s states",
    },
    {
        LOG_ARPRATELIMIT_4_ABNORMAL,
        E_WARNING,
        "ARPRATELIMIT-ABNORMAL",
        "The port %s recieve %d packets on %s in 30s, exceed configured value %d",
    },
    {
        LOG_ARPNUMBERLIMIT_4_EXCEED,
        E_WARNING,
        "ARPNUMBERLIMIT-EXCEED",
        "%s",
    },
    {
        LOG_ARPNUMBERLIMIT_4_ABNORMAL,
        E_WARNING,
        "ARPNUMBERLIMIT-ABNORMAL",
        "The port %s is suffered %llu attack in the 30 seconds",
    },
    {
        LOG_MONITOR_3_LATENCY_START,
        E_ERROR,
        "MONITOR-LATENCY_START",
        "Interface %s reachs to max latency event threshold, average latency is %llu ns",
    },
    {
        LOG_MONITOR_4_LATENCY_END,
        E_WARNING,
        "MONITOR-LATENCY_END",
        "Interface %s falls to min latency event threshold, average latency is %llu ns",
    },
    {
        LOG_MONITOR_3_BUFFER_START,
        E_ERROR,
        "MONITOR-BUFFER_START",
        "Interface %s reachs to max buffer event threshold, buffer count is %u",
    },
    {
        LOG_MONITOR_4_BUFFER_END,
        E_WARNING,
        "MONITOR-BUFFER_END",
        "Interface %s falls to min buffer event threshold, buffer count is %u",
    },
    {
        LOG_VRRP_4_VRRP_STATE,
        E_WARNING,
        "VRRP-VRRP_STATE",
        "VRRP instance %d for interface %s state changes (%s -> %s)",
    },
    {
        LOG_OSPF_4_LSA_ROUTE,
        E_WARNING,
        "OSPF-LSA_ROUTE",
        "OSPF lsa %s %s %s ignored for %s",
    },
    {
        LOG_SSM_5_PORT_SELECT,
        E_NOTICE,
        "SSM-PORT_SELECT",
        "The port %s is selected as the best clock resource.",
    },
    {
        LOG_SSM_4_STATE_CHANGE,
        E_WARNING,
        "SSM-STATE_CHANGE",
        "The device synce state is changed from %s to %s",
    },
    {
        LOG_PTP_4_PTP_STATE_CHANGE,
        E_WARNING,
        "PTP-PTP_STATE_CHANGE",
        "PTP state of interface %s is changing from %s to %s",
    },
    {
        LOG_PTP_4_PTP_MASTER_CHANGE,
        E_WARNING,
        "PTP-PTP_MASTER_CHANGE",
        "PTP master of interface %s changed to clock %s",
    },
    {
        LOG_PTP_4_PTP_ACCURACY_CHANGE,
        E_WARNING,
        "PTP-PTP_ACCURACY_CHANGE",
        "PTP master accuracy changed to 0x%s",
    },
    {
        LOG_IPSLA_4_IPSLA_EVENT,
        E_WARNING,
        "IPSLA-IPSLA_EVENT",
        "Entry id %d, test id %d, test result change from %s to %s",
    },
    {
        LOG_TRACK_4_TRACK_EVENT,
        E_WARNING,
        "TRACK-TRACK_EVENT",
        "State change to %s for track %d",
    },
    {
        LOG_TRACK_4_STATIC_RT_UPDATE,
        E_WARNING,
        "TRACK-STATIC_RT_UPDATE",
        "Set %s for ip %s/%d nh %s",
    },
    {
        LOG_OAM_4_TPOAM_CCM_STATE_CHANGE,
        E_WARNING,
        "OAM-TPOAM_CCM_STATE_CHANGE",
        "CCM state of oam session %d is changing from %s to %s",
    },
    {
        LOG_OAM_4_TPOAM_LM_EVENT,
        E_WARNING,
        "OAM-TPOAM_LM_EVENT",
        "LM event %s of oam session %d, local rx frame loss %u, local rx frame loss ratio %u.%u, remote rx frame loss %u, remote rx frame loss ratio %u.%u",
    },
    {
        LOG_OAM_4_TPOAM_DM_EVENT,
        E_WARNING,
        "OAM-TPOAM_DM_EVENT",
        "DM event %s of oam session %d, delay %u, variation %u",
    },
    {
        LOG_OAM_4_G8131_LINK_CHANGE,
        E_WARNING,
        "OAM-G8131_LINK_CHANGE",
        "%s aps group id %u change to %s link",
    },
    {
        LOG_ND_4_G8131_LINK_CHANGE,
        E_WARNING,
        "ND-G8131_LINK_CHANGE",
        "IPv6 Neigh overflow",
    },
    {
        LOG_RMON_4_RISING_ALARM,
        E_WARNING,
        "RMON-RISING_ALARM",
        "Alarm Index %d Alarm Rising Threshold %d Alarm Value %lld Alarm Rising Event Index %d",
    },
    {
        LOG_RMON_4_FALLING_ALARM,
        E_WARNING,
        "RMON-FALLING_ALARM",
        "Alarm Index %d Alarm Falling Threshold %d Alarm Value %lld Alarm Falling Event Index %d",
    },
    {
        LOG_OAM_4_G8032_STATE_CHANGE,
        E_WARNING,
        "OAM-G8032_STATE_CHANGE",
        "G8032 ring  %u change from %s state to %s state",
    },
    {
        LOG_OAM_4_G8032_CONFIG_ALARM,
        E_WARNING,
        "OAM-G8032_CONFIG_ALARM",
        "There are more than one rpl owner node in G8032 ring  %d",
    },
};

#endif /* !__GENLOG_ID_PRIV_H__ */

