/* Copyright (C) 2000-2009  Centec networks, Inc. All Rights Reserved. */

#ifndef _ZEBOS_STM_SNMP_H
#define _ZEBOS_STM_SNMP_H

/* STM-MIB. */
#define STMMIB SNMP_ENTERPRISE_COMMON_OID, 33

#define STMMIBOBJECT_STMCURRENTTYPE  1
#define STMMIBOBJECT_STMNEXTTYPE  2
#define STM_SHOW_PROFILETYPE  1
#define STM_SHOW_VLANNUMBER  2
#define STM_SHOW_VLANFORWARDINGINSTANCES  3
#define STM_SHOW_UCASTMACADDRESSES  4
#define STM_SHOW_MCASTMACADDRESSES  5
#define STM_SHOW_BLACKHOLEMACADDRESSES  6
#define STM_SHOW_MAXAPPLIEDVLANMAPPING  7
#define STM_SHOW_CFMLOCALANDREMOTEMEPS  8
#define STM_SHOW_G8031GROUPS  9
#define STM_SHOW_G8032RINGS  10
#define STM_SHOW_MACBASEDVLANCLASSIFICATION  11
#define STM_SHOW_IPV4BASEDVLANCLASSIFICATION  12
#define STM_SHOW_IPV6BASEDVLANCLASSIFICATION  13
#define STM_SHOW_IPV4HOSTROUTES  14
#define STM_SHOW_INDIRECTIPV4ROUTES  15
#define STM_SHOW_IPV4ECMPGROUPS  16
#define STM_SHOW_IPV6HOSTROUTES  17
#define STM_SHOW_INDIRECTIPV6ROUTES  18
#define STM_SHOW_IPV6ECMPGROUPS  19
#define STM_SHOW_IPTUNNELPEERS  20
#define STM_SHOW_NATFORIVIPEERS  21
#define STM_SHOW_IPV4MCASTROUTES  22
#define STM_SHOW_IPV4MCASTTOTALMEMBERS  23
#define STM_SHOW_IPV6MCASTROUTES  24
#define STM_SHOW_IPV6MCASTTOTALMEMBERS  25
#define STM_SHOW_IPV4SOURCEGUARDENTRIES  26
#define STM_SHOW_IPV6SOURCEGUARDENTRIES  27
#define STM_SHOW_IPV4ACLANDQOSFLOWENTRIES  28
#define STM_SHOW_IPV6ACLANDQOSFLOWENTRIES  29
#define STM_SHOW_FTN  30
#define STM_SHOW_INCOMINGLABELMAP  31
#define STM_SHOW_VPWS  32
#define STM_SHOW_LSPPE  33
#define STM_SHOW_LSPP  34
#define STM_SHOW_VPLSPEER  35
#define STM_SHOW_VPLSAC  36
#define STM_SHOW_VPLSINSTANCE  37
#define STM_SHOW_LSPOAM  38
#define STM_SHOW_OAMFORPSEUDOWRIE  39
#define STM_SHOW_MPLSAPSTUNNEL  40

#define STM_BOOT_CONFIG_HARDWARE  50        /*provide default hardware configure*/

#define STM_FALSE   0
#define STM_TRUE    1


#define CHSM_STM_SNMP_RETURN_INTEGER(V) \
  do { \
    *var_len = sizeof (int); \
    snmp_api_int_val = V; \
    return (u_char *) &snmp_api_int_val; \
  } while (0)

void stm_snmp_init (struct lib_globals *);
void stm_snmp_init_all (struct lib_globals *zg);	

#endif /* _ZEBOS_CHSM_SNMP_H */

