#!/bin/sh
 asn1c -Werror -fnative-types -funnamed-unions \
 ../common/hal_msg_types.asn1 \
 ../common/hal_msg_stats.asn1 \
 ../common/hal_msg_debug.asn1 \
 ../common/hal_msg_mirror.asn1 \
 ../common/hal_msg_loopback.asn1 \
 ../common/hal_msg_cpu_traffic.asn1 \
 ../common/hal_msg_bfd.asn1 \
 ../tap/hal_msg_tap.asn1 \
 ../intf/hal_msg_if.asn1 \
 ../intf/hal_msg_l3if.asn1 \
 ../l2/hal_msg_l2_types.asn1 \
 ../l3/hal_msg_l3_types.asn1 \
 ../l3/hal_msg_ivi.asn1 \
 ../l2/hal_msg_vlan.asn1 \
 ../l2/hal_msg_agg.asn1 \
 ../l2/hal_msg_vlan_mapping.asn1 \
 ../l2/hal_msg_mef.asn1 \
 ../l2/hal_msg_eth_oam.asn1 \
 ../l2/hal_msg_vlan_classifier.asn1 \
 ../l2/hal_msg_ip_binding.asn1 \
 ../l2/hal_msg_bridge.asn1 \
 ../l2/hal_msg_l2mc.asn1 \
 ../l2/hal_msg_ratelimit.asn1 \
 ../l2/hal_msg_dot1x.asn1 \
 ../l2/hal_msg_vlan_security.asn1 \
 ../l2/hal_msg_phy_loopback.asn1 \
 ../l2/hal_msg_oam_efm.asn1 \
 ../l2/hal_msg_g8031.asn1 \
 ../l2/hal_msg_g8032.asn1 \
 ../hsrv2AgtMsg.asn1 \
 ../hagt2SrvMsg.asn1 \
 ../l3/hal_msg_tunnel.asn1 \
 ../l3/hal_msg_ecmp.asn1 \
 ../l3/hal_msg_ipuc.asn1 \
 ../l3/hal_msg_l3mc.asn1 \
 ../l3/hal_msg_vrrp.asn1 \
 ../l3/hal_msg_pbr.asn1 \
 ../misc/hal_msg_ptp.asn1 \
 ../misc/hal_msg_efd.asn1 \
 ../misc/hal_msg_synce.asn1 \
 ../misc/hal_msg_sflow.asn1 \
 ../misc/hal_msg_iptables.asn1 \
 ../mpls/hal_msg_mpls.asn1 \
 ../mpls/hal_msg_tpoam.asn1 \
 ../aclqos/hal_msg_flow.asn1 \
 ../aclqos/hal_msg_acl.asn1 \
 ../aclqos/hal_msg_qos.asn1 \
 ../openflow/hal_msg_openflow_port.asn1 \
 ../openflow/hal_msg_openflow_flow.asn1 \
 ../openflow/hal_msg_openflow_nexthop.asn1 \
 ../openflow/hal_msg_openflow_group.asn1 \
 ../openflow/hal_msg_openflow_stats.asn1 \
 ../openflow/hal_msg_openflow_parser.asn1 \
 ../openflow/hal_msg_openflow_linkagg.asn1 \
 ../openflow/hal_msg_openflow_tunnel.asn1 \
 ../openflow/hal_msg_openflow_meter.asn1 \
 ../openflow/hal_msg_openflow_bond.asn1 \
 ../openflow/hal_msg_openflow_queue.asn1 \
2>&1| grep -v "contents unchanged" | grep -v "Cannot read file-dependencies"
