include $(MK_DIR)/sys.mk
LIB = fan
SRCS  = fan_api.c
SRCS  += fan_drv.c

include $(DRV_TOP_DIR)/Makefile.include
CPPFLAGS += -I$(DRV_TOP_DIR)/device/fan
CPPFLAGS += -I$(DRV_TOP_DIR)/device/log
CPPFLAGS += -I$(DRV_TOP_DIR)/bus/cpu/i2c/include
CPPFLAGS += -I$(DRV_TOP_DIR)/bus/cpu/spi/include
CPPFLAGS += -I$(DRV_TOP_DIR)/device/epld

include $(MK_DIR)/lib.mk
