#ifndef __LCSH_ERROR_H__
#define __LCSH_ERROR_H__
#include "glb_const.h"

enum lcsh_err
{
    LCSH_E_NONE = 0,
    LCSH_E_NO_MEMORY = GLB_LCSH_ERROR_BASE,
    LCSH_E_INVALID_PARAM,
    LCSH_E_INVALID_PTR,
    LCSH_E_SOCK_CREATE_ERR,
    LCSH_E_SOCK_OPT_ERR,
    LCSH_E_SOCK_BIND_ERR,
    LCSH_E_SOCK_ACCEPT_ERR,
    LCSH_E_SOCK_READ_ERR,
    LCSH_E_SOCK_SEND_ERR,
    LCSH_E_SOCK_CONNECT_ERR,
    LCSH_E_MSG_LEN_TOO_LONG,
    LCSH_E_MSG_TYPE_EER,
    LCSH_E_NOT_INIT,
    LCSH_E_SOCK_WRITE_ERR,
    LCSH_E_ENTRY_NOT_EXIST,
    LCSH_E_ENTRY_EXIST,
    LCSH_E_RESOURCE_FULL,
    LCSH_E_CREATE_INTF_FAILED,
    LCSH_E_ADD_INTF_FAILED,
    LCSH_E_EXCEED_MAX_MAC_NUM,
    LCSH_E_FDB_ENTRY_NOT_EXIT,
    LCSH_E_EXCEED_MAX_SIZE,
    LCSH_E_INTF_ISNT_L2,
    LCSH_E_PTP_INVALID_IFTYPE,
    LCSH_E_MAX
};


#endif /*__LCSH_ERROR_H__*/
