include $(MK_DIR)/sys.mk

LIB = asicmdio
SRCS  = mdio.c

include $(DRV_TOP_DIR)/Makefile.include
CPPFLAGS += -I$(SDK_DIR)/sal/include
CPPFLAGS += -I$(DRV_TOP_DIR)/bus/cpu/spi/include
CPPFLAGS += -I$(DRV_TOP_DIR)/bus/cpu/i2c/include
CPPFLAGS += -I$(DRV_TOP_DIR)/bus/asic/mdio
CPPFLAGS += -I$(DRV_TOP_DIR)/device/epld
CPPFLAGS += -I$(DRV_TOP_DIR)/drvio/${MY_CPU_DIR}/ctc_hw

include $(MK_DIR)/lib.mk
