#!/bin/sh
#
# ide 0.01 2007/05/14 13:44:09 (Zhu Jian)
#
# Initialize or shutdown a cf ATA/IDE adapter
#
# The first argument should be either 'insert' or 'remove'.Called by cf_monitor daemon 

#declare -rx SCRIPT=${0##*/}

if [ `whoami` != "root" ]; then
    echo "You must run this as root"
    exit 1
fi

mntpoint=/mnt/cf

#function success {
#    rmmod ide-ctc.ko
#    success=1
#    debug "$mntpoint unmounted\n"
#    exit 0
#}

# print verbose/debug information
#function debug {
#    if [ -n "$verbose" ]; then
#        printf "$1"
#    fi
#}

case "$1" in

'insert')
    #inmod=`insmod /lib/ide-ctc.ko 2>&1`
    insmod /lib/ide-ctc.ko 
    ret=$?
    if [ $ret -lt 0 ]; then
        printf "can not probe the dev" >&2
        exit 1
    fi
    if [ ! -e $mntpoint ]; then
        mkdir $mntpoint
    fi
    mount -t vfat /dev/hda1 $mntpoint 
    if [ "$?" != "0" ];then
        rmmod ide-ctc.ko
        echo "mount cf card failed!"
        logger -p crit "mount cf card failed!"
        rm -rf $mntpoint
        exit 1
    fi
    echo "$mntpoint mounted"
    logger -p info "$mntpoint mounted"
    ;;

'remove')
    tryumount=`umount $mntpoint 2>&1`
    ret=$?
    if [ "`echo $tryumount |grep 'not mounted'`" ]; then
    	printf "%s is not mounted\n" "$mntpoint" >&2
        rmmod ide-ctc   
        exit 1
    fi
    
    if [ "`echo $tryumount |grep 'not found'`" ]; then
    	printf "%s not fount\n" "$mntpoint" >&2
        rmmod ide-ctc
    	exit 1
    fi
    
    # did the umount succeed?
    if [ $ret -eq 0 ]; then
    	#success
        rmmod ide-ctc.ko
        echo "$mntpoint umounted\n"
        logger -p info "$mntpoint mounted"
        rm -rf $mntpoint
        exit 0
    else
    	# if the filesystem is busy, kill all processes accessing it
    	if [ "`echo $tryumount |grep 'busy'`" ]; then
    	    echo "busy... killing all processes accessing the filesystem\n"
            logger -p crit "busy... killing all processes accessing the filesystem"
    	    while [ ! -z "`fuser -m $mntpoint`" ]; do
    	       fuser -k $mntpoint &> /dev/null
               sleep 3
            done
    	else
    	    rmmod ide-ctc
    	    printf "%s failed... umount returned %d\n" "$SCRIPT" "$ret" >&2
            rm -rf $mntpoint
    	    exit 1
    	fi
    fi
    
    # try to umount again
    tryumount=`umount $mntpoint 2>&1`
    ret=$?
    if [ $ret -eq 0 ]; then
    	#success
        rmmod ide-ctc.ko
        echo "$mntpoint umounted\n"
        logger -p info "$mntpoint mounted"
        rm -rf $mntpoint
        exit 0
    else
        logger -p alert "ALARM!!! OPERATE CF CARD FAILED!!!"
    fi

    ;;

esac

exit 0
